server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: mapper/*.xml